[build]
  # Linux shell on Netlify: rm works
  command = "rm -f .env .env.* && npx @11ty/eleventy"
  publish = "_site"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  # optional belt-and-braces for the scanner (shouldn’t be needed after rm)
  SECRETS_SCAN_OMIT_PATHS = ".env,.env.*"
