[build]
  command = "npx @11ty/eleventy"
  publish = "_site"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
